spring.application.name=websocket
spring.threads.virtual.enabled=true

server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5433/teste
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#IA
spring.ai.google.genai.api-key={}
spring.ai.google.genai.chat.options.model=gemini-3.5-flash

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=gemma4:e2b
